### ISSUE TITLE
script for blender2.8

### ISSUE THREAD

**Issue by BlenderCN** [Moguri/BlenderPanda#46]
hello,I make some simple changes to make it useful for blender2.80,but,which can't export pam,why? Here is 
https://github.com/BlenderCN/BlenderPanda_28

**Comment by Moguri** [comment]
Could you please provide a list of changes you made? It is difficult for me to tell based on the commit history what has changed.

Also, in the future, it is better to start with a fork of this project and make edits rather than starting a new repo and copying the files over. This way you can create a pull request to easily upstream your changes.

**Comment by Moguri** [comment]
Closing this in favor of #48
